-- Explore All Objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

/*Dimensions Explortion
Identify the unique values in each dimensions.
Recognize how data might be grouped or segmented which is useful for later analysis*/

-- Explore all countries come from
SELECT DISTINCT country FROM gold.dim_customers;

-- Explore All Categories "The major divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3;

--Date Exploration
--Find the date of 1st and last order
SELECT MIN(order_date) AS first_order_date, MAX(order_date) AS last_order_date,
DATEDIFF(year, MIN(order_date),mAX(order_date)) AS order_range_years
FROM gold.fact_sales

--Find the youngest and oldest customer
SELECT MIN(birthdate) AS youngest_birthdate, MAX(birthdate) AS oldest_birthdate
FROM gold.dim_customers;

--Measures Exploration
--Find the total sales
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales;

--Find how many items are sold
SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales;

-- Find average selling price
SELECT AVG(price) AS avg_price 
FROM gold.fact_sales;

-- Find total number of orders
SELECT COUNT(order_number) AS total_orders
FROM gold.fact_sales;
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales;

-- Find the total number of products
SELECT COUNT(product_key) AS total_products
FROM gold.dim_products;

--FIND the total number of customers
SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers;

--Find the total  number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers 
FROM gold.fact_sales;

--Magnitude
--Find total customers by countries
SELECT country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

--Find total customers by gender
SELECT gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by categories
SELECT category, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category;

--What is the average costs in  each category
SELECT category, AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs;

--What is the total revenue generated by each customers
SELECT p.category, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category;

--What is the total revenue generated by each customer
SELECT c.customer_key,c.first_name, c.last_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,c.first_name, c.last_name;

--What is the distribution of items across countries 
SELECT c.country, SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- RANKING
-- Which 5 products generate the highest revenue
SELECT TOP 5
p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- What are the 5 worst-performing products in terms of sales
SELECT TOP 5
p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue;

--Trends and Change over time
--Sales performance over time

SELECT FORMAT(order_date, 'YYYY-mmm') as order_date, SUM(sales_amount)AS total_sales
,COUNT(DISTINCT customer_key) AS total_customers,
SUM(quantity) as total_quantity
FROM  gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY FORMAT(order_date, 'yyyy-mmm')
ORDER BY FORMAT(order_date, 'YYYY-mmm');

--Cumulative Analysis
--The total sales per month and the running total of sales over time
SELECT order_date,
total_sales,
SUM(total_sales) OVER(PARTITION BY order_date ORDER BY order_date) AS running_total,
AVG(avg_price)  OVER(PARTITION BY order_date ORDER BY order_date) AS moving_average
FROM
(SELECT 
DATETRUNC(month,order_date) AS order_date,
SUM(sales_amount) AS total_sales,
AVG(price) AS avg_price
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month,order_date)) AS t;

--Performance Analysis (Comparing the current value with target value)
--Analyse the yearly performance of products by comparing each products sales to both it's average sales performance and the previous year's sales
WITH yearly_product_sales AS (SELECT
YEAR(f.order_date) AS order_year,
p.product_name,
SUM(f.sales_amount) AS current_sales
FROM gold.fact_sales AS f LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
WHERE order_date IS NOT NULL
GROUP BY YEAR(f.order_date), p.product_name)

SELECT order_year,
product_name,
current_sales,
AVG(current_sales) OVER(PARTITION BY product_name) AS avg_sales, 
current_sales - AVG(current_sales) OVER(PARTITION BY product_name) AS diff_avg,
CASE WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) > 0 THEN 'Above Avg'
	 WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) < 0 THEN 'Below Avg'
	 ELSE 'Avg'
END AS avg_change,
LAG(current_sales) OVER(Partition BY product_name ORDER BY order_year) AS pre_year_sales,
CASE WHEN current_sales - LAG(current_sales) OVER(Partition BY product_name ORDER BY order_year) > 0 THEN 'Increasing'
	 WHEN current_sales - LAG(current_sales) OVER(Partition BY product_name ORDER BY order_year) < 0 THEN 'Decreasing'
	 ELSE 'No Change'
END AS year_change
FROM yearly_product_sales;

--PART TO WHOLE ANALYSIS
--Which categories contribute the most to overall sales
WITH category_sales AS (
SELECT category,
SUM(sales_amount) AS total_sales
FROM gold.fact_sales AS f LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY category)

SELECT category, total_sales, SUM(total_sales) OVER() AS overall_sales,
CONCAT(ROUND((CAST(total_sales  AS  FLOAT) / SUM(total_sales) OVER())*100,2),'%') AS percentage_of_total
FROM category_sales
ORDER BY percentage_of_total;

-- Data segmentation
-- Group the data based on specific range
-- Segment prroducts into cost ranges annd count how many  products fallninto each category
WITH products_segnments AS (SELECT product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'BELOW 100'
	 WHEN cost BETWEEN 100 AND 1000 THEN '100-1000'
	 ELSE 'ABOVE 1000'
END cost_range
FROM gold.dim_products)

SELECT cost_range, COUNT(product_key) AS total_products
FROM products_segnments
GROUP BY cost_range;

/* Group Customers into 3 segments based on their spending behaviour
 -VIP : At least 12 months of history and spending more than 5,000
 -Regulare :  At least 12 months of history and spending less than 5,000
 -New : lifespan less than 12 months
And find the total number of customers by each group
*/
WITH customer_spendings AS (SELECT 
c.customer_key,
SUM(f.sales_amount) AS total_spendings,
MIN(order_date) AS first_order,
MAX(order_date) AS last_order,
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan
FROM gold.fact_sales AS f LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key)

SELECT
CASE WHEN lifespan >=12 AND total_spendings >=5000 THEN 'VIP'
	 WHEN lifespan >=12 AND total_spendings< 5000 THEN 'Regular'
	 ELSE 'New'
END  AS customer_segment,
COUNT(customer_key) AS total_customers
FROM customer_spendings
GROUP BY CASE WHEN lifespan >=12 AND total_spendings >=5000 THEN 'VIP'
	 WHEN lifespan >=12 AND total_spendings <5000 THEN 'Regular'
	 ELSE 'New'
END ;